name: Vercel Production Deployment
on:
  push:
    branches:
      - main

jobs:
  check-author:
    runs-on: ubuntu-latest
    outputs:
      is-authorized: ${{ steps.check.outputs.is-authorized }}
    steps:
      - name: Check commit author
        id: check
        run: |
          AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
          echo "Commit author: $AUTHOR_EMAIL"
          if [[ "$AUTHOR_EMAIL" == "s223188874@deakin.edu.au" ]]; then
            echo "is-authorized=true" >> $GITHUB_OUTPUT
          else
            echo "is-authorized=false" >> $GITHUB_OUTPUT
          fi

  deploy-production:
    needs: check-author
    if: needs.check-author.outputs.is-authorized == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} 